### ISSUE TITLE
click_link: special character # in url

### ISSUE THREAD

**Issue by rjurado01** [dockyard/capybara-email#56]
I have this html in my email body:

```
<a href=\"http://127.0.0.1:49559/#/password?reset_password_token=12345678\">Reset password</a>
```

When I do click_link('Reset password') it redirect to: http://127.0.0.1:49559/
It seems that cuts url when find '#'.

Any help?

**Comment by michaeldupuisjr** [comment]
@rjurado01 Sorry for the delay in responding to this. `click_link` is implemented by [capybara](https://github.com/jnicklas/capybara) in this library. You may want open up an issue on that repo, or if it has been resolved, please let me know the issue #. Thanks!
