### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by andrewhavens** [DockYard/capybara-email#60]
Can you please release a new version? 2.4.0 was released July 7, 2014. Looks like there have been a few useful commits since then that would be nice to make public.

**Comment by bcardarella** [comment]
@andrewhavens sure thing! We're no longer doing active ruby development. If you or someone else you know would like to collab on the project to keep it alive I'm happy to add :)

**Comment by bcardarella** [comment]
I just released 2.5.0

**Comment by andrewhavens** [comment]
@bcardarella Sure, I wouldn't mind being a designated maintainer. I think this gem is pretty useful and have already spent some time getting familiar with the codebase.

**Comment by bcardarella** [comment]
@andrewhavens great, added you as a collaborator
